### ISSUE TITLE
Update wiki templates of en-test.opensuse.org

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/wiki#13]
Finally I have time to check en-test.opensuse.org . Here are two typical pages:

1. https://en-test.opensuse.org/Portal:Distribution
2. https://en-test.opensuse.org/Firefox

Both use some wiki template, styled in Common.css . Their styles don't match the new skin well. Next step, I plan:

1. Modify all important templates so that they use styles from new skin.
2. Clean and move Common.css styles to skin CSS.

**Comment by cboltz** [comment]
Just as a quick note - we have about 20 wikis, so keeping the CSS class names might be easier than adjusting the templates in all the wikis ;-)

The styles in Mediawiki:Common.css are used in (IIRC) 3 or 4 wikis (english + some wikis that include Mediawiki:Common.css from the english wiki). 

(I spend some evenings "only" to replace `<feed>` with `<rss>` in all wikis, so I can imagine how long it will take to update all templates...)

Moving the Common.css styles into the skin CSS files if of course a good idea, no doubt about that.

**Comment by guoyunhe** [comment]
Updating template is necessary but not urgent. For example, `Infobox` template contains many `#if` condition that will generate empty lines and its package download links always expire when new Leap released.

We could keep classes/styles of the old template but also provide new classes/styles in CSS. English wiki can be updated, and then call maintainers of other wikis to edit these templates. If some wiki's template is not updated, they can still be rendered very well.

**Comment by guoyunhe** [comment]
Many templates have been updated. Maybe this issue is too general to follow. Let's make issues for each single template that should be updated.
