### ISSUE TITLE
Fix related links in mobile view

### ISSUE THREAD

**Issue by hellcp** [openSUSE/wiki#19]
![screenshot from 2018-05-10 01-12-58](https://user-images.githubusercontent.com/30577011/39844254-5f7d3fd4-53ef-11e8-9290-e564bfdde135.png)
Links in mobile view escape the border ;)

Visible on https://en-test.opensuse.org/Main_Page with narrow width.

**Comment by cboltz** [comment]
This is https://en.opensuse.org/Template:Portal_footer which is currently a table with 5 columns. Someone will have to edit that template ;-)

**Comment by hellcp** [comment]
Oh, that's right ;/

**Comment by guoyunhe** [comment]
It has been fixed in English wiki.
