### ISSUE TITLE
Use grid system to fix table overflow and support mobile view

### ISSUE THREAD

**Issue by GroverChouT** [openSUSE/wiki#22]
Currently on small width view:

![image](https://user-images.githubusercontent.com/8392630/40558300-71fd863a-6085-11e8-9982-09107ea676a1.png)

Since we now use bootstrap we can fix it by grid system.

**Comment by Huy-Ngo** [comment]
![image](https://user-images.githubusercontent.com/19296926/92445959-538d6d80-f1df-11ea-9113-37814ff8072d.png)

I think this issue is resolved, since after resizing the list automatically collapse into fewer columns. Please close this issue if that is the case.
