### ISSUE TITLE
Layout issues on Special:Recentchanges

### ISSUE THREAD

**Issue by cboltz** [openSUSE/wiki#27]
https://en.opensuse.org/Special:RecentChanges uses different column width for every row, which means the page doesn't look nice.

After investigation, I found out that each row is a separate table, which at least explains why the columns are not aligned. I forced `td` to have a blue border and made a screenshot:

![screenshot_20180920_131206](https://user-images.githubusercontent.com/146882/45814749-d8bba700-bcd6-11e8-868e-0f8e05c59c17.png)

Also note that lines covering multiple changes have an additional column on the left, which makes applying a fixed width to the timestamp column more interesting[tm] ;-)

**Comment by guoyunhe** [comment]
I guess it is caused by some Bootstrap table style override. I will fix it later today.
