### ISSUE TITLE
SVG uploading errors

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/wiki#29]
I uploaded a SVG file https://en.opensuse.org/File:Picard_icon.svg and the server has some errors related to ImageMagick:

```
Error creating thumbnail: /bin/bash: convert: command not found
```

Maybe we still need ImageMagick, or we disable SVG uploading.

**Comment by guoyunhe** [comment]
@cboltz , Do you think which solution we should take:

1. Disable SVG uploading to avoid errors and waste of storage space.
2. Install and enable ImageMagick so MediaWiki can generate thumbnails for SVG images.

**Comment by cboltz** [comment]
The wiki supports SVG files since a long time - I just forgot to update this issue ;-)
