### ISSUE TITLE
Warning background color overlays infobox

### ISSUE THREAD

**Issue by cboltz** [openSUSE/wiki#31]
See https://en.opensuse.org/Dropbox for an example - the `{{warning}}` background color overlays the infobox.

Please adjust the z-index ;-)

**Comment by guoyunhe** [comment]
I fixed that by adding "overflow: auto" to alert box templates. It will have a nice space between alert and infobox.

![screenshot_2018-10-06 dropbox - opensuse](https://user-images.githubusercontent.com/5836790/46568462-ec5d4380-c94d-11e8-9dd6-b8f255848d88.png)

**Comment by guoyunhe** [comment]
@cboltz Can we close this issue?

**Comment by cboltz** [comment]
Yes, thanks! :-)
