### ISSUE TITLE
Chameleon skin does not define "shell" CSS class

### ISSUE THREAD

**Issue by Qantas94Heavy** [openSUSE/wiki#36]
There are some pages that use [Template:Shell](https://en.opensuse.org/Template:Shell), but no formatting is applied as there is no `shell` CSS class in the Chameleon skin.

Should we add this back, or just replace them with `<pre>`, `<code>`or something like that?

**Comment by guoyunhe** [comment]
I have updated the template 
![image](https://user-images.githubusercontent.com/5836790/51806855-b12daa00-2287-11e9-95bb-c93574af2f33.png)

**Comment by guoyunhe** [comment]
@Qantas94Heavy Can you confirm if the issue has been solved? If so, we can close this issue. Otherwise, we can continue debug. Thanks!

**Comment by Qantas94Heavy** [comment]
Mostly resolved :+1: Only slight issue is that MediaWiki link formatting in `{{Shell}}` has no effect, i.e.:

```mediawiki
{{Shell|[https://build.opensuse.org/package/show/openSUSE%3ATools/osc-plugin-install osc-plugin-install] devel:tools rpmdevtools}}
```

gets rendered as

    [https://build.opensuse.org/package/show/openSUSE%3ATools/osc-plugin-install osc-plugin-install] devel:tools rpmdevtools

**Comment by guoyunhe** [comment]
This is because MediaWiki doesn't render any wiki code in `<pre>` tags. For your use case, you can move the link out of the shell block.

```
[https://build.opensuse.org/package/show/openSUSE%3ATools/osc-plugin-install Download osc-plugin-install]

{{Shell| osc-plugin-install devel:tools rpmdevtools}}
```

**Comment by guoyunhe** [comment]
@Qantas94Heavy I updated the template and some css. You should be able to add link in Shell template now. Remember to [clean up browser cache](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#w_clear-the-cache).

**Comment by Qantas94Heavy** [comment]
Thanks for that! I think we can close this now.
