### ISSUE TITLE
print layout is broken

### ISSUE THREAD

**Issue by cboltz** [openSUSE/wiki#40]
I just tried to print a wiki page (to a PDF), and the result is not really useable:
- on the left, 1/3 of the page is covered by the menu column (but only the search input field is visible)
- the page content gets only printed on the first page, and is then cut off
- the second page only contains the footer menu (links to other *.o.o pages)

A screenshot of the "printed" PDF probably explains it best:
![Screenshot_20190414_224954](https://user-images.githubusercontent.com/146882/56098993-a63df980-5f07-11e9-8d7a-77ef1303836b.png)

That's what Firefox 66 produces.

Chromium is doing better (it doesn't cut off the content after the first page), but still has the superfluous left column.

Ideally,
- the left column should be hidden
- the Page/Discussion/Edit/History/... menu should be hidden
- the footer menu shouldn't be printed (but the copyright footer should stay)
- and obviously the content shouldn't be cut off ;-)

**Comment by guoyunhe** [comment]
Indeed a problem. Usually a wiki theme will ship a `print.css` which will only be loaded when printing. I will work on this feature recently. Should be easy, just remove some navigation element and reduce light gray and low contrast elements (usually terrible in printed paper).

**Comment by cboltz** [comment]
This is fixed with the latest pull requests - thanks!

I just deployed the updated code to all wikis.
