### ISSUE TITLE
table of contents has "position:sticky", but scrolls away

### ISSUE THREAD

**Issue by cboltz** [openSUSE/wiki#41]
The TOC (table of contents) in the right column has position:sticky and overflow:auto, therefore I'd expect that it stays always visible. However, when scrolling down, it scrolls away.

The screenshot shows https://en.opensuse.org/openSUSE:Packaging_checks - other pages are also affected, but with a shorter TOC that doesn't need scrollbars it's less visible that the TOC shouldn't scroll away.

![Screenshot_20190415_223006](https://user-images.githubusercontent.com/146882/56163347-6261f780-5fce-11e9-9ee4-18b28c35af9b.png)

**Comment by guoyunhe** [comment]
Possible reason is that the `#toc`'s parent has `overflow: hidden;` which disabled any `position: sticky;` of children. I will check it.

**Comment by cboltz** [comment]
This was fixed with your pull requests - thanks!

Deployed now.
