### ISSUE TITLE
Wrong text color in tables with enabled dark mode

### ISSUE THREAD

**Issue by EGD** [openSUSE/wiki#53]
source in [en.oo wiki](https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Detect_a_distribution_flavor_for_special_code)
![Screenshot_20200105_160933](https://user-images.githubusercontent.com/720688/71780641-36f8c000-2fd6-11ea-9774-25492af8a96a.png)

**Comment by guoyunhe** [comment]
This is a bug in https://github.com/openSUSE/chameleon

**Comment by cboltz** [comment]
@guoyunhe I've seen your changes in chameleon, but it looks like it wasn't enough.

Some quick testing shows that you'll also need

    .table, body.mediawiki .knowledge, body.mediawiki table {
        color: inherit;
    }

**Comment by guoyunhe** [comment]
Yes. The SaSS code is not very clear when I wrote it. I hope the third commit fix it.

**Comment by guoyunhe** [comment]
Should be fixed. Ctrl+F5 to refresh.

**Comment by cboltz** [comment]
Thanks, the table looks good now :-)
