### ISSUE TITLE
TOC got lost with update to chameleon 3.0

### ISSUE THREAD

**Issue by cboltz** [openSUSE/wiki#61]
The wikis no longer have a TOC (table of contents) in the right column. (Thanks to Axel for noticing this!)

Bisecting shows that the TOC was lost in commit 212eba5828b65596e5b938ed209d2b0d97d97e4b ("update to chameleon 3.0") - but I'm not sure if it's caused by something on the wiki side or by a change in chameleon.

I somewhat doubt that this was an intentional change, so - can you please bring the TOC back? ;-)

**Comment by guoyunhe** [comment]
Should be fixed. There was a JavaScript error that prevents other functions.

**Comment by cboltz** [comment]
Wow, that was fast! :-)

Thanks!
